.TH WB "1" "January 2023" "GNU/UNIX Vocabulary Application" "Vocabulary Application"
.SH NAME
wb \- take vocabulary notes and do operations on them
.SH SYNOPSIS
.B wb
[\fI\,OPTION\/\fR]... [\fI\,DATA\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
take vocabulary notes and manage them by using listing, deletion, insertion and showing functions.
.TP
\fB\-a\fR, \fB\-\-add\fR
add words by using a ncurses menu
.TP
\fB\-l\fR, \fB\-\-list\fR
list words by using a ncurses menu
.TP
\fB\-E\fR, \fB\-\-export\fR
export application data
.TP
\fB\-I\fR, \fB\-\-import\fR
import application data
.TP
\fB\-d [DATA]\fR, \fB\-\-delete [DATA]\fR
delete the word
.TP
\fB\-w [DATA]\fR, \fB\-\-word [DATA]\fR
show the word
.TP
\fB\-h\fR, \fB\-\-help\fR
output a help menu
.TP
\fB\-v\fR, \fB\-\-version\fR
output the application version
.TP
\fB\-g\fR, \fB\-\-github\fR
output a github menu
.SH AUTHOR
Written by Mehmet Mert Gunduz.
.SH "REPORTING BUGS"
Open an issue: <https://github.com/MertGunduz/wb/issues/new/>
.SH COPYRIGHT
Copyright \(co 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
Full documentation <https://mertgunduz.github.io/wb/index.html>
.br